import { EditorView } from '@codemirror/view'
import { Extension } from '@codemirror/state'
import { HighlightStyle, syntaxHighlighting } from '@codemirror/language'
import { tags as t } from '@lezer/highlight'

export type ThemeId =
  | 'tokyo-night-storm'
  | 'tokyo-night-night'
  | 'catppuccin-latte'
  | 'catppuccin-frappe'
  | 'catppuccin-macchiato'
  | 'catppuccin-mocha'
  | 'rose-pine'
  | 'rose-pine-moon'
  | 'rose-pine-dawn'

export interface ThemeDefinition {
  id: ThemeId
  label: string
  family: 'Tokyo Night' | 'Catppuccin' | 'Rosé Pine'
  appearance: 'dark' | 'light'
  colors: Record<string, string>
}

export type FontPresetId =
  | 'focal-default'
  | 'literary'
  | 'bookish'
  | 'minimal'

export interface FontPreset {
  id: FontPresetId
  label: string
  fonts: Record<string, string>
}

export const defaultThemeId: ThemeId = 'tokyo-night-storm'
export const defaultFontPresetId: FontPresetId = 'focal-default'

export const themeOptions: ThemeDefinition[] = [
  {
    id: 'tokyo-night-storm',
    label: 'Tokyo Night Storm',
    family: 'Tokyo Night',
    appearance: 'dark',
    colors: {
      '--tn-bg': '#1f2335',
      '--tn-bg-dark': '#16161e',
      '--tn-bg-highlight': '#292e42',
      '--tn-bg-popup': '#24283b',
      '--tn-terminal-black': '#414868',
      '--tn-fg': '#c0caf5',
      '--tn-fg-dark': '#a9b1d6',
      '--tn-fg-muted': '#787c99',
      '--tn-fg-gutter': '#3b4261',
      '--tn-comment': '#565f89',
      '--tn-blue': '#7aa2f7',
      '--tn-cyan': '#7dcfff',
      '--tn-cyan2': '#73daca',
      '--tn-teal': '#73daca',
      '--tn-green': '#9ece6a',
      '--tn-magenta': '#bb9af7',
      '--tn-orange': '#ff9e64',
      '--tn-red': '#f7768e',
      '--tn-yellow': '#e0af68',
      '--tn-white': '#c0caf5',
      '--tn-selection': 'rgba(122, 162, 247, 0.20)',
      '--tn-cursor': '#c0caf5',
      '--accent-rgb': '125, 207, 255',
      '--overlay-scrim': 'rgba(8, 10, 18, 0.66)',
      '--toolbar-bg': 'rgba(22, 22, 30, 0.9)',
      '--toolbar-bg-hover': 'rgba(36, 40, 59, 0.96)',
      '--panel-bg': 'rgba(36, 40, 59, 0.96)',
      '--panel-border': 'rgba(255, 255, 255, 0.08)',
      '--surface-shadow': '0 24px 80px rgba(0, 0, 0, 0.42)',
      '--accent-solid': '#7dcfff',
      '--accent-solid-hover': '#93d8ff',
      '--accent-contrast': '#101827',
      '--syntax-keyword': '#bb9af7',
      '--syntax-name': '#c0caf5',
      '--syntax-function': '#7dcfff',
      '--syntax-constant': '#ff9e64',
      '--syntax-definition': '#c0caf5',
      '--syntax-type': '#e0af68',
      '--syntax-operator': '#73daca',
      '--syntax-link': '#7dcfff',
      '--syntax-comment': '#565f89',
      '--syntax-heading': '#c0caf5',
      '--syntax-atom': '#ff9e64',
      '--syntax-string': '#9ece6a',
      '--syntax-invalid': '#f7768e',
    },
  },
  {
    id: 'tokyo-night-night',
    label: 'Tokyo Night Night',
    family: 'Tokyo Night',
    appearance: 'dark',
    colors: {
      '--tn-bg': '#1a1b26',
      '--tn-bg-dark': '#16161e',
      '--tn-bg-highlight': '#24283b',
      '--tn-bg-popup': '#1f2335',
      '--tn-terminal-black': '#414868',
      '--tn-fg': '#c0caf5',
      '--tn-fg-dark': '#a9b1d6',
      '--tn-fg-muted': '#787c99',
      '--tn-fg-gutter': '#3b4261',
      '--tn-comment': '#565f89',
      '--tn-blue': '#7aa2f7',
      '--tn-cyan': '#7dcfff',
      '--tn-cyan2': '#73daca',
      '--tn-teal': '#73daca',
      '--tn-green': '#9ece6a',
      '--tn-magenta': '#bb9af7',
      '--tn-orange': '#ff9e64',
      '--tn-red': '#f7768e',
      '--tn-yellow': '#e0af68',
      '--tn-white': '#c0caf5',
      '--tn-selection': 'rgba(122, 162, 247, 0.18)',
      '--tn-cursor': '#c0caf5',
      '--accent-rgb': '122, 162, 247',
      '--overlay-scrim': 'rgba(7, 8, 14, 0.7)',
      '--toolbar-bg': 'rgba(22, 22, 30, 0.92)',
      '--toolbar-bg-hover': 'rgba(31, 35, 53, 0.98)',
      '--panel-bg': 'rgba(31, 35, 53, 0.97)',
      '--panel-border': 'rgba(255, 255, 255, 0.08)',
      '--surface-shadow': '0 24px 80px rgba(0, 0, 0, 0.5)',
      '--accent-solid': '#7aa2f7',
      '--accent-solid-hover': '#89afff',
      '--accent-contrast': '#0f1320',
      '--syntax-keyword': '#bb9af7',
      '--syntax-name': '#c0caf5',
      '--syntax-function': '#7aa2f7',
      '--syntax-constant': '#ff9e64',
      '--syntax-definition': '#c0caf5',
      '--syntax-type': '#e0af68',
      '--syntax-operator': '#73daca',
      '--syntax-link': '#7dcfff',
      '--syntax-comment': '#565f89',
      '--syntax-heading': '#c0caf5',
      '--syntax-atom': '#ff9e64',
      '--syntax-string': '#9ece6a',
      '--syntax-invalid': '#f7768e',
    },
  },
  {
    id: 'catppuccin-latte',
    label: 'Catppuccin Latte',
    family: 'Catppuccin',
    appearance: 'light',
    colors: {
      '--tn-bg': '#eff1f5',
      '--tn-bg-dark': '#e6e9ef',
      '--tn-bg-highlight': '#dce0e8',
      '--tn-bg-popup': '#e6e9ef',
      '--tn-terminal-black': '#9ca0b0',
      '--tn-fg': '#4c4f69',
      '--tn-fg-dark': '#5c5f77',
      '--tn-fg-muted': '#6c6f85',
      '--tn-fg-gutter': '#8c8fa1',
      '--tn-comment': '#7c7f93',
      '--tn-blue': '#1e66f5',
      '--tn-cyan': '#179299',
      '--tn-cyan2': '#04a5e5',
      '--tn-teal': '#179299',
      '--tn-green': '#40a02b',
      '--tn-magenta': '#8839ef',
      '--tn-orange': '#fe640b',
      '--tn-red': '#d20f39',
      '--tn-yellow': '#df8e1d',
      '--tn-white': '#4c4f69',
      '--tn-selection': 'rgba(30, 102, 245, 0.14)',
      '--tn-cursor': '#4c4f69',
      '--accent-rgb': '30, 102, 245',
      '--overlay-scrim': 'rgba(76, 79, 105, 0.22)',
      '--toolbar-bg': 'rgba(255, 250, 243, 0.92)',
      '--toolbar-bg-hover': 'rgba(230, 233, 239, 0.98)',
      '--panel-bg': 'rgba(255, 250, 243, 0.98)',
      '--panel-border': 'rgba(76, 79, 105, 0.12)',
      '--surface-shadow': '0 24px 80px rgba(76, 79, 105, 0.14)',
      '--accent-solid': '#1e66f5',
      '--accent-solid-hover': '#2b74ff',
      '--accent-contrast': '#ffffff',
      '--syntax-keyword': '#8839ef',
      '--syntax-name': '#4c4f69',
      '--syntax-function': '#1e66f5',
      '--syntax-constant': '#fe640b',
      '--syntax-definition': '#4c4f69',
      '--syntax-type': '#df8e1d',
      '--syntax-operator': '#179299',
      '--syntax-link': '#1e66f5',
      '--syntax-comment': '#7c7f93',
      '--syntax-heading': '#4c4f69',
      '--syntax-atom': '#fe640b',
      '--syntax-string': '#40a02b',
      '--syntax-invalid': '#d20f39',
    },
  },
  {
    id: 'catppuccin-frappe',
    label: 'Catppuccin Frappe',
    family: 'Catppuccin',
    appearance: 'dark',
    colors: {
      '--tn-bg': '#303446',
      '--tn-bg-dark': '#232634',
      '--tn-bg-highlight': '#414559',
      '--tn-bg-popup': '#292c3c',
      '--tn-terminal-black': '#626880',
      '--tn-fg': '#c6d0f5',
      '--tn-fg-dark': '#b5bfe2',
      '--tn-fg-muted': '#a5adce',
      '--tn-fg-gutter': '#737994',
      '--tn-comment': '#838ba7',
      '--tn-blue': '#8caaee',
      '--tn-cyan': '#99d1db',
      '--tn-cyan2': '#85c1dc',
      '--tn-teal': '#81c8be',
      '--tn-green': '#a6d189',
      '--tn-magenta': '#ca9ee6',
      '--tn-orange': '#ef9f76',
      '--tn-red': '#e78284',
      '--tn-yellow': '#e5c890',
      '--tn-white': '#c6d0f5',
      '--tn-selection': 'rgba(140, 170, 238, 0.20)',
      '--tn-cursor': '#c6d0f5',
      '--accent-rgb': '140, 170, 238',
      '--overlay-scrim': 'rgba(24, 26, 36, 0.7)',
      '--toolbar-bg': 'rgba(35, 38, 52, 0.9)',
      '--toolbar-bg-hover': 'rgba(41, 44, 60, 0.96)',
      '--panel-bg': 'rgba(41, 44, 60, 0.97)',
      '--panel-border': 'rgba(255, 255, 255, 0.08)',
      '--surface-shadow': '0 24px 80px rgba(17, 17, 27, 0.45)',
      '--accent-solid': '#8caaee',
      '--accent-solid-hover': '#9cb7f5',
      '--accent-contrast': '#10131d',
      '--syntax-keyword': '#ca9ee6',
      '--syntax-name': '#c6d0f5',
      '--syntax-function': '#8caaee',
      '--syntax-constant': '#ef9f76',
      '--syntax-definition': '#c6d0f5',
      '--syntax-type': '#e5c890',
      '--syntax-operator': '#99d1db',
      '--syntax-link': '#8caaee',
      '--syntax-comment': '#838ba7',
      '--syntax-heading': '#c6d0f5',
      '--syntax-atom': '#ef9f76',
      '--syntax-string': '#a6d189',
      '--syntax-invalid': '#e78284',
    },
  },
  {
    id: 'catppuccin-macchiato',
    label: 'Catppuccin Macchiato',
    family: 'Catppuccin',
    appearance: 'dark',
    colors: {
      '--tn-bg': '#24273a',
      '--tn-bg-dark': '#1e2030',
      '--tn-bg-highlight': '#363a4f',
      '--tn-bg-popup': '#2b2f44',
      '--tn-terminal-black': '#5b6078',
      '--tn-fg': '#cad3f5',
      '--tn-fg-dark': '#b8c0e0',
      '--tn-fg-muted': '#a5adcb',
      '--tn-fg-gutter': '#6e738d',
      '--tn-comment': '#8087a2',
      '--tn-blue': '#8aadf4',
      '--tn-cyan': '#8bd5ca',
      '--tn-cyan2': '#91d7e3',
      '--tn-teal': '#8bd5ca',
      '--tn-green': '#a6da95',
      '--tn-magenta': '#c6a0f6',
      '--tn-orange': '#f5a97f',
      '--tn-red': '#ed8796',
      '--tn-yellow': '#eed49f',
      '--tn-white': '#cad3f5',
      '--tn-selection': 'rgba(138, 173, 244, 0.18)',
      '--tn-cursor': '#cad3f5',
      '--accent-rgb': '138, 173, 244',
      '--overlay-scrim': 'rgba(18, 19, 30, 0.72)',
      '--toolbar-bg': 'rgba(30, 32, 48, 0.9)',
      '--toolbar-bg-hover': 'rgba(43, 47, 68, 0.96)',
      '--panel-bg': 'rgba(43, 47, 68, 0.97)',
      '--panel-border': 'rgba(255, 255, 255, 0.08)',
      '--surface-shadow': '0 24px 80px rgba(17, 17, 27, 0.46)',
      '--accent-solid': '#8aadf4',
      '--accent-solid-hover': '#99b8fb',
      '--accent-contrast': '#0f1220',
      '--syntax-keyword': '#c6a0f6',
      '--syntax-name': '#cad3f5',
      '--syntax-function': '#8aadf4',
      '--syntax-constant': '#f5a97f',
      '--syntax-definition': '#cad3f5',
      '--syntax-type': '#eed49f',
      '--syntax-operator': '#8bd5ca',
      '--syntax-link': '#8aadf4',
      '--syntax-comment': '#8087a2',
      '--syntax-heading': '#cad3f5',
      '--syntax-atom': '#f5a97f',
      '--syntax-string': '#a6da95',
      '--syntax-invalid': '#ed8796',
    },
  },
  {
    id: 'catppuccin-mocha',
    label: 'Catppuccin Mocha',
    family: 'Catppuccin',
    appearance: 'dark',
    colors: {
      '--tn-bg': '#1e1e2e',
      '--tn-bg-dark': '#181825',
      '--tn-bg-highlight': '#313244',
      '--tn-bg-popup': '#24273a',
      '--tn-terminal-black': '#585b70',
      '--tn-fg': '#cdd6f4',
      '--tn-fg-dark': '#bac2de',
      '--tn-fg-muted': '#a6adc8',
      '--tn-fg-gutter': '#6c7086',
      '--tn-comment': '#7f849c',
      '--tn-blue': '#89b4fa',
      '--tn-cyan': '#89dceb',
      '--tn-cyan2': '#94e2d5',
      '--tn-teal': '#94e2d5',
      '--tn-green': '#a6e3a1',
      '--tn-magenta': '#cba6f7',
      '--tn-orange': '#fab387',
      '--tn-red': '#f38ba8',
      '--tn-yellow': '#f9e2af',
      '--tn-white': '#cdd6f4',
      '--tn-selection': 'rgba(137, 180, 250, 0.18)',
      '--tn-cursor': '#cdd6f4',
      '--accent-rgb': '137, 180, 250',
      '--overlay-scrim': 'rgba(10, 10, 17, 0.74)',
      '--toolbar-bg': 'rgba(24, 24, 37, 0.9)',
      '--toolbar-bg-hover': 'rgba(36, 39, 58, 0.96)',
      '--panel-bg': 'rgba(36, 39, 58, 0.97)',
      '--panel-border': 'rgba(255, 255, 255, 0.08)',
      '--surface-shadow': '0 24px 80px rgba(17, 17, 27, 0.5)',
      '--accent-solid': '#89b4fa',
      '--accent-solid-hover': '#9ac0ff',
      '--accent-contrast': '#101320',
      '--syntax-keyword': '#cba6f7',
      '--syntax-name': '#cdd6f4',
      '--syntax-function': '#89b4fa',
      '--syntax-constant': '#fab387',
      '--syntax-definition': '#cdd6f4',
      '--syntax-type': '#f9e2af',
      '--syntax-operator': '#94e2d5',
      '--syntax-link': '#89b4fa',
      '--syntax-comment': '#7f849c',
      '--syntax-heading': '#cdd6f4',
      '--syntax-atom': '#fab387',
      '--syntax-string': '#a6e3a1',
      '--syntax-invalid': '#f38ba8',
    },
  },
  {
    id: 'rose-pine',
    label: 'Rosé Pine',
    family: 'Rosé Pine',
    appearance: 'dark',
    colors: {
      '--tn-bg': '#191724',
      '--tn-bg-dark': '#16141f',
      '--tn-bg-highlight': '#26233a',
      '--tn-bg-popup': '#1f1d2e',
      '--tn-terminal-black': '#524f67',
      '--tn-fg': '#e0def4',
      '--tn-fg-dark': '#908caa',
      '--tn-fg-muted': '#6e6a86',
      '--tn-fg-gutter': '#403d52',
      '--tn-comment': '#6e6a86',
      '--tn-blue': '#31748f',
      '--tn-cyan': '#9ccfd8',
      '--tn-cyan2': '#ebbcba',
      '--tn-teal': '#9ccfd8',
      '--tn-green': '#31748f',
      '--tn-magenta': '#c4a7e7',
      '--tn-orange': '#f6c177',
      '--tn-red': '#eb6f92',
      '--tn-yellow': '#f6c177',
      '--tn-white': '#e0def4',
      '--tn-selection': 'rgba(196, 167, 231, 0.18)',
      '--tn-cursor': '#e0def4',
      '--accent-rgb': '196, 167, 231',
      '--overlay-scrim': 'rgba(11, 10, 16, 0.72)',
      '--toolbar-bg': 'rgba(22, 20, 31, 0.9)',
      '--toolbar-bg-hover': 'rgba(31, 29, 46, 0.96)',
      '--panel-bg': 'rgba(31, 29, 46, 0.97)',
      '--panel-border': 'rgba(255, 255, 255, 0.08)',
      '--surface-shadow': '0 24px 80px rgba(8, 7, 12, 0.48)',
      '--accent-solid': '#c4a7e7',
      '--accent-solid-hover': '#cfb4ee',
      '--accent-contrast': '#201b2d',
      '--syntax-keyword': '#c4a7e7',
      '--syntax-name': '#e0def4',
      '--syntax-function': '#9ccfd8',
      '--syntax-constant': '#f6c177',
      '--syntax-definition': '#e0def4',
      '--syntax-type': '#ebbcba',
      '--syntax-operator': '#9ccfd8',
      '--syntax-link': '#9ccfd8',
      '--syntax-comment': '#6e6a86',
      '--syntax-heading': '#e0def4',
      '--syntax-atom': '#f6c177',
      '--syntax-string': '#31748f',
      '--syntax-invalid': '#eb6f92',
    },
  },
  {
    id: 'rose-pine-moon',
    label: 'Rosé Pine Moon',
    family: 'Rosé Pine',
    appearance: 'dark',
    colors: {
      '--tn-bg': '#232136',
      '--tn-bg-dark': '#1f1d2e',
      '--tn-bg-highlight': '#2a273f',
      '--tn-bg-popup': '#2a273f',
      '--tn-terminal-black': '#59546d',
      '--tn-fg': '#e0def4',
      '--tn-fg-dark': '#908caa',
      '--tn-fg-muted': '#6e6a86',
      '--tn-fg-gutter': '#44415a',
      '--tn-comment': '#6e6a86',
      '--tn-blue': '#3e8fb0',
      '--tn-cyan': '#9ccfd8',
      '--tn-cyan2': '#ea9a97',
      '--tn-teal': '#9ccfd8',
      '--tn-green': '#3e8fb0',
      '--tn-magenta': '#c4a7e7',
      '--tn-orange': '#f6c177',
      '--tn-red': '#eb6f92',
      '--tn-yellow': '#ea9a97',
      '--tn-white': '#e0def4',
      '--tn-selection': 'rgba(196, 167, 231, 0.16)',
      '--tn-cursor': '#e0def4',
      '--accent-rgb': '196, 167, 231',
      '--overlay-scrim': 'rgba(13, 12, 19, 0.72)',
      '--toolbar-bg': 'rgba(31, 29, 46, 0.9)',
      '--toolbar-bg-hover': 'rgba(42, 39, 63, 0.96)',
      '--panel-bg': 'rgba(42, 39, 63, 0.97)',
      '--panel-border': 'rgba(255, 255, 255, 0.08)',
      '--surface-shadow': '0 24px 80px rgba(9, 8, 14, 0.48)',
      '--accent-solid': '#c4a7e7',
      '--accent-solid-hover': '#cfb4ee',
      '--accent-contrast': '#1d1930',
      '--syntax-keyword': '#c4a7e7',
      '--syntax-name': '#e0def4',
      '--syntax-function': '#9ccfd8',
      '--syntax-constant': '#f6c177',
      '--syntax-definition': '#e0def4',
      '--syntax-type': '#ea9a97',
      '--syntax-operator': '#9ccfd8',
      '--syntax-link': '#9ccfd8',
      '--syntax-comment': '#6e6a86',
      '--syntax-heading': '#e0def4',
      '--syntax-atom': '#f6c177',
      '--syntax-string': '#3e8fb0',
      '--syntax-invalid': '#eb6f92',
    },
  },
  {
    id: 'rose-pine-dawn',
    label: 'Rosé Pine Dawn',
    family: 'Rosé Pine',
    appearance: 'light',
    colors: {
      '--tn-bg': '#faf4ed',
      '--tn-bg-dark': '#fffaf3',
      '--tn-bg-highlight': '#f2e9e1',
      '--tn-bg-popup': '#fffaf3',
      '--tn-terminal-black': '#9893a5',
      '--tn-fg': '#575279',
      '--tn-fg-dark': '#6e6a86',
      '--tn-fg-muted': '#797593',
      '--tn-fg-gutter': '#9893a5',
      '--tn-comment': '#9893a5',
      '--tn-blue': '#286983',
      '--tn-cyan': '#56949f',
      '--tn-cyan2': '#d7827e',
      '--tn-teal': '#56949f',
      '--tn-green': '#286983',
      '--tn-magenta': '#907aa9',
      '--tn-orange': '#ea9d34',
      '--tn-red': '#b4637a',
      '--tn-yellow': '#d7827e',
      '--tn-white': '#575279',
      '--tn-selection': 'rgba(144, 122, 169, 0.14)',
      '--tn-cursor': '#575279',
      '--accent-rgb': '144, 122, 169',
      '--overlay-scrim': 'rgba(87, 82, 121, 0.18)',
      '--toolbar-bg': 'rgba(255, 250, 243, 0.92)',
      '--toolbar-bg-hover': 'rgba(242, 233, 225, 0.98)',
      '--panel-bg': 'rgba(255, 250, 243, 0.98)',
      '--panel-border': 'rgba(87, 82, 121, 0.12)',
      '--surface-shadow': '0 24px 80px rgba(87, 82, 121, 0.12)',
      '--accent-solid': '#907aa9',
      '--accent-solid-hover': '#9f89b7',
      '--accent-contrast': '#fffaf3',
      '--syntax-keyword': '#907aa9',
      '--syntax-name': '#575279',
      '--syntax-function': '#56949f',
      '--syntax-constant': '#ea9d34',
      '--syntax-definition': '#575279',
      '--syntax-type': '#d7827e',
      '--syntax-operator': '#56949f',
      '--syntax-link': '#286983',
      '--syntax-comment': '#9893a5',
      '--syntax-heading': '#575279',
      '--syntax-atom': '#ea9d34',
      '--syntax-string': '#286983',
      '--syntax-invalid': '#b4637a',
    },
  },
]

export const themes = Object.fromEntries(themeOptions.map((theme) => [theme.id, theme])) as Record<ThemeId, ThemeDefinition>

export const fontPresetOptions: FontPreset[] = [
  {
    id: 'focal-default',
    label: 'Focal Default',
    fonts: {
      '--font-prose': "'iA Writer Quattro', Georgia, 'Times New Roman', serif",
      '--font-mono': "'JetBrains Mono', 'Menlo', monospace",
      '--font-ui': "-apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif",
    },
  },
  {
    id: 'literary',
    label: 'Literary',
    fonts: {
      '--font-prose': "Georgia, 'Times New Roman', serif",
      '--font-mono': "'JetBrains Mono', 'Menlo', monospace",
      '--font-ui': "-apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif",
    },
  },
  {
    id: 'bookish',
    label: 'Bookish',
    fonts: {
      '--font-prose': "'Palatino Linotype', 'Book Antiqua', Palatino, Georgia, serif",
      '--font-mono': "'JetBrains Mono', 'Menlo', monospace",
      '--font-ui': "-apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif",
    },
  },
  {
    id: 'minimal',
    label: 'Minimal',
    fonts: {
      '--font-prose': "ui-serif, Georgia, serif",
      '--font-mono': "ui-monospace, 'SFMono-Regular', 'JetBrains Mono', monospace",
      '--font-ui': "system-ui, sans-serif",
    },
  },
]

export const fontPresets = Object.fromEntries(
  fontPresetOptions.map((preset) => [preset.id, preset])
) as Record<FontPresetId, FontPreset>

export function isThemeId(value: string): value is ThemeId {
  return value in themes
}

export function isFontPresetId(value: string): value is FontPresetId {
  return value in fontPresets
}

export function applyTheme(themeId: ThemeId) {
  if (typeof document === 'undefined') return
  const root = document.documentElement
  const theme = themes[themeId]
  root.dataset.theme = themeId
  root.style.colorScheme = theme.appearance
  for (const [key, value] of Object.entries(theme.colors)) {
    root.style.setProperty(key, value)
  }
}

export function applyFontPreset(fontPresetId: FontPresetId) {
  if (typeof document === 'undefined') return
  const root = document.documentElement
  const preset = fontPresets[fontPresetId]
  root.dataset.fontPreset = fontPresetId
  for (const [key, value] of Object.entries(preset.fonts)) {
    root.style.setProperty(key, value)
  }
}

export const tokyoNightTheme: Extension = EditorView.theme(
  {
    '&': {
      color: 'var(--tn-fg)',
      backgroundColor: 'transparent',
    },
    '.cm-content': {
      caretColor: 'var(--tn-cursor)',
      fontFamily: 'var(--font-prose)',
    },
    '.cm-cursor': {
      borderLeftColor: 'var(--tn-cursor)',
      borderLeftWidth: '2px',
    },
    '.cm-selectionBackground': {
      backgroundColor: 'var(--tn-selection)',
    },
    '&.cm-focused .cm-selectionBackground': {
      backgroundColor: 'var(--tn-selection)',
    },
    '.cm-panels': {
      backgroundColor: 'var(--tn-bg-dark)',
      color: 'var(--tn-fg)',
    },
    '.cm-activeLine': {
      backgroundColor: 'transparent',
    },
    '.cm-gutters': {
      display: 'none',
    },
  },
  { dark: true }
)

export const tokyoNightHighlight = syntaxHighlighting(
  HighlightStyle.define([
    { tag: t.keyword,                                                                      color: 'var(--syntax-keyword)' },
    { tag: [t.name, t.deleted, t.character, t.propertyName, t.macroName],                 color: 'var(--syntax-name)' },
    { tag: [t.function(t.variableName), t.labelName],                                     color: 'var(--syntax-function)' },
    { tag: [t.color, t.constant(t.name), t.standard(t.name)],                             color: 'var(--syntax-constant)' },
    { tag: [t.definition(t.name), t.separator],                                           color: 'var(--syntax-definition)' },
    { tag: [t.typeName, t.className, t.number, t.changed, t.annotation, t.modifier,
             t.self, t.namespace],                                                         color: 'var(--syntax-type)' },
    { tag: [t.operator, t.operatorKeyword, t.escape, t.regexp, t.special(t.string)],      color: 'var(--syntax-operator)' },
    { tag: [t.url, t.link],                                                                color: 'var(--syntax-link)', textDecoration: 'underline' },
    { tag: [t.meta, t.comment],                                                            color: 'var(--syntax-comment)', fontStyle: 'italic' },
    { tag: t.strong,                                                                       fontWeight: 'bold' },
    { tag: t.emphasis,                                                                     fontStyle: 'italic' },
    { tag: t.strikethrough,                                                                textDecoration: 'line-through' },
    { tag: t.heading,                                                                      fontWeight: 'bold', color: 'var(--syntax-heading)' },
    { tag: [t.atom, t.bool, t.special(t.variableName)],                                   color: 'var(--syntax-atom)' },
    { tag: [t.processingInstruction, t.string, t.inserted],                               color: 'var(--syntax-string)' },
    { tag: t.invalid,                                                                      color: 'var(--syntax-invalid)' },
  ])
)
