allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
doc-valid-idents = ["VoiceOver", "AppKit", "AccessKit", "FSEvents", "MkDocs", "VitePress", "GitLab", "GitHub", "LaTeX", "MathJax", "TeX", "PlantUML", "GeoJSON", "TopoJSON", "WaveDrom", "WebKit", ".."]
